config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#landing'
  resources :people
  resources :hobbies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :person
  validates :description, presence: true
  validates :confirm, :acceptance => true
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
  validates :gender, presence: true
  validates :name, :format => { :with => /\A[a-zA-Z]+\z/,
    :message => "Only letters allowed" }
    validates :gender, :format => { :with => /\A[a-zA-Z]+\z/,
      :message => "Only letters allowed" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1
  # GET /hobbies/1.json
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to @hobby, notice: 'Hobby was successfully created.' }
        format.json { render :show, status: :created, location: @hobby }
      else
        format.html { render :new }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to @hobby, notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
        params.require(:hobby).permit(:description, :person_id, :confirm)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :gender)
    end
end

app/controllers/static_controller.rb
class StaticController <ApplicationController
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/hobbies/_form.html.erb
<%= form_with(model: hobby, local: true) do |form| %>
  <% if hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hobby.errors.count, "error") %> prohibited this hobby from being saved:</h2>

      <ul>
      <% hobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form.label :description %>
<%= form.text_field :description %>
<%= form.label :person_id %>
<%= form.number_field :person_id %>
<div class="field">
  <%= form.label :confirm %>
  <%= form.check_box :confirm %>

</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hobbies/edit.html.erb
<h1>Editing Hobby</h1>

<%= render 'form', hobby: @hobby %>

<%= link_to 'Show', @hobby %> |
<%= link_to 'Back', hobbies_path %>

app/views/hobbies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hobbies</h1>

<table class= 'table'>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hobbies.each do |hobby| %>
      <tr>
        <td><%= hobby.description %></td>
        <td><%= link_to 'Show', hobby %></td>
        <td><%= link_to 'Edit', edit_hobby_path(hobby) %></td>
        <td><%= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hobby', new_hobby_path %>

app/views/hobbies/new.html.erb
<h1>New Hobby</h1>

<%= render 'form', hobby: @hobby %>

<%= link_to 'Back', hobbies_path %>

app/views/hobbies/show.html.erb
<p id="notice"><%= notice %></p>
<%= @hobby.description %>
<%= link_to 'Edit', edit_hobby_path(@hobby) %> |
<%= link_to 'Back', hobbies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArAssociation</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <ul class="nav">
  <li role="presentation" class="active"><a href="/">Home</a></li>
  <br>
  <li role="presentation"><a href="/people">People</a></li>
  <br>
  <li role="presentation"><a href="/hobbies">Hobby</a></li>
</ul>

  <%= yield %>
</body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <%=form.label :name  %>
    <%=form.text_field :name  %>
</div>
<div>
  <%=form.label :gender  %>
    <%=form.text_field :gender  %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class= 'table'>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.gender %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @person.name %></h1>
<h1><%= @person.gender %></h1>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>